### ISSUE TITLE
verify.sh's iOS lane can pass on a commit CI rejects: a Darwin-only API in a cross-compiled module reached CI through the local gate

### ISSUE THREAD

**Issue by yogesh-dhande** [yogesh-dhande/spaces#315]
## Observed

`scripts/verify.sh` passed locally on a commit whose `ios-tests` lane CI rejected with a hard compile error:

```
apps/macos/Sources/spacesterminalcore/SpacesProfile.swift:174:28: error: 'homeDirectoryForCurrentUser' is unavailable in iOS
** TEST BUILD FAILED **
```

`verify.sh` is the established pre-commit gate, so a Darwin-only API entering a module that cross-compiles for iOS can currently get through it and only be caught after push.

## The capability is not missing

`verify.sh` backgrounds `ios-test-lane.sh`, which runs `build-for-testing` over the same target, and the iOS app depends on `spacesterminalcore` directly (`apps/ios/project.yml`). A direct build does catch it — verified by building against a scratch DerivedData:

```
xcodebuild -project apps/ios/SpacesMobile.xcodeproj -scheme SpacesMobile \
  -destination 'generic/platform=iOS Simulator' -derivedDataPath <scratch> build
```

With the offending line present that build fails with the identical error CI reported; without it, it succeeds. So the lane's command covers the module.

## Suspected cause

The shared DerivedData. `docs/dev.md` states `apps/macos/.build/ios-derived-data` is reused incrementally across runs rather than cleaned, and this repo has a prior recorded incident of a stale iOS module cache serving a pre-change `spacesterminalcore` across worktrees.

This is a hypothesis, not a confirmed cause — the local pass was not reproduced after the fact, because by then the source was corrected.

## How to confirm

Next time the local iOS lane disagrees with CI:

1. `rm -rf apps/macos/.build/ios-derived-data`
2. Re-run the lane on the same source.

If that reproduces the CI failure, incremental reuse is the gap.

## Decision if confirmed

Whether the lane should clean, or invalidate on a `spacesterminalcore` source change, rather than reuse unconditionally. Reuse exists for speed, so the fix should be the narrowest thing that makes the gate trustworthy — invalidating on changes to the cross-compiled sources rather than always cleaning.

A gate that can pass on code CI rejects is worse than a slower gate, because it moves the failure to after the push and after any local claim that verify passed.

**Comment by yogesh-dhande** [comment]
A second instance, worse than the iOS one, on the same root cause — `scripts/verify.sh` covers macOS and iOS only.

A change to `spacesterminalcore` passed `verify.sh` locally and passed CI's `verify` and `ios-tests` lanes, but **crashed the Linux `spacesd` binary at startup**: SIGSEGV, core dumped, both architectures.

```
0  _CFIsSwift + 9                                   in libFoundation.so
1  CFArrayGetCount + 21                             in libFoundation.so
2  CFBundleGetAllBundles + 229                      in libFoundation.so
3  static Bundle.allBundlesRegardlessOfType.getter  in libFoundation.so
4  static Bundle.allBundles.getter                  in libFoundation.so
```

`Bundle.allBundles` segfaults on Linux. Confirmed by A/B on the real daemon binary in the same container, one line differing: exit 0 with the call removed, exit 139 with it reintroduced.

This is worse than the iOS case in two ways. The iOS gap produced a **compile error**, which fails loudly the moment CI runs. This produced a **runtime crash on a supported platform**, which only the smoke test catches — a change that crashed the daemon slightly later in startup, or only under some condition, could plausibly get further.

So the scope here is broader than "the iOS lane reuses DerivedData": the local gate does not exercise Linux at all, and `spacesterminalcore` cross-compiles to it. `apps/macos/scripts/run_linux_tests.sh` exists and runs the lane in Docker, so the capability is there — it is not wired into `verify.sh`.

Worth deciding: whether `verify.sh` should run the Linux lane when the diff touches a cross-compiled module. It is slow, so unconditionally is probably wrong, but the current state is that a whole platform's runtime behaviour is only ever checked after push.

**Comment by yogesh-dhande** [comment]
## The DerivedData hypothesis is disproven

Forced the reproduction rather than waiting for a natural recurrence.

**Setup:** a checkout whose `apps/macos/.build/ios-derived-data` (1.1 GB) had just produced a green `scripts/verify.sh`, so incremental reuse was at its most favourable — exactly the state the hypothesis says can serve a stale `spacesterminalcore`.

**Injected** into `SpacesProfile.accountHomeDirectoryPath()`, a function iOS compiles unconditionally:

```swift
_ = FileManager.default.homeDirectoryForCurrentUser
```

**Ran** `apps/macos/scripts/ios-test-lane.sh` against that warm DerivedData — the same script `verify.sh` backgrounds.

**Result:** the lane recompiled the file and failed.

```
SpacesProfile.swift:219:33: error: 'homeDirectoryForCurrentUser' is unavailable in iOS
NSFileManager.h:461:35: note: 'homeDirectoryForCurrentUser' has been explicitly marked unavailable here
** TEST BUILD FAILED **
```

Exit 65. The lane caught it on the first try, from warm DerivedData, with no cleaning. Incremental reuse is not the hole, and there is no case for making the lane clean or invalidate on cross-compiled source changes.

## The likelier explanation

The premise of this issue — that `verify.sh` passed locally on the offending commit — is most likely a reporting error rather than a gate failure.

The verify runs of that period were invoked as `scripts/verify.sh > log 2>&1; echo "EXIT=$?"`. That compound command always exits 0, and the reported code was the harness's, not the script's. At least one other run in the same period was reported as passing when the script had in fact exited 1, and was corrected only afterwards. So the gate very probably did reject this commit and the failure was misread.

The invocation has since changed to `exec scripts/verify.sh > log 2>&1` with no trailing command, so the exit code observed is the script's own.

## Suggested disposition

Close as not-a-defect in the lane. The capability was never missing — this issue itself recorded that a direct `xcodebuild` catches the error — and the lane is now shown to catch it under the exact conditions the hypothesis blamed. What remains worth keeping from this issue is the general point that a gate which can be *believed* to have passed is as dangerous as one that can actually pass, which is addressed separately by #324's lane summary.

**Comment by yogesh-dhande** [comment]
Closing as not-a-defect in the lane.

## The hypothesis was tested and disproven

This issue proposed that `verify.sh`'s iOS lane could pass on a commit CI rejects because `apps/macos/.build/ios-derived-data` is reused incrementally rather than cleaned, and that a stale `spacesterminalcore` could therefore be served to the lane.

Rather than wait for a natural recurrence, the failure was forced. A checkout whose iOS DerivedData (1.1 GB) had just produced a green `scripts/verify.sh` — incremental reuse at its most favourable, exactly the state the hypothesis blames — had a Darwin-only API injected into `SpacesProfile.accountHomeDirectoryPath()`, a function iOS compiles unconditionally:

```swift
_ = FileManager.default.homeDirectoryForCurrentUser
```

Running `apps/macos/scripts/ios-test-lane.sh` — the same script `verify.sh` backgrounds — against that warm DerivedData recompiled the file and failed:

```
SpacesProfile.swift:219:33: error: 'homeDirectoryForCurrentUser' is unavailable in iOS
NSFileManager.h:461:35: note: 'homeDirectoryForCurrentUser' has been explicitly marked unavailable here
** TEST BUILD FAILED **
```

Exit 65, first attempt, no cleaning. Incremental reuse is not the hole, and there is no case for making the lane clean or invalidate on cross-compiled source changes — which would have cost every developer a full iOS rebuild per run in exchange for nothing.

## The likelier explanation for the original observation

The premise — that `verify.sh` passed locally on the offending commit — was most probably a reporting error rather than a gate failure.

The verify runs of that period were invoked as:

```
scripts/verify.sh > log 2>&1; echo "EXIT=$?"
```

That compound command always exits 0, and the value being read was the harness's, not the script's. At least one other run in the same window was reported as passing when the script had in fact exited 1, and was corrected only afterwards. So the gate very probably did reject this commit, and the failure was misread as a pass.

The invocation has since changed to `exec scripts/verify.sh > log 2>&1` with no trailing command, so the exit code observed is the script's own.

## What was worth keeping

The general point behind this issue — that a gate which can be *believed* to have passed is as dangerous as one that can actually pass — was real, and is addressed separately in #324: `verify.sh` now closes every run with a lane summary naming what each lane did (`NOT STARTED` / `DID NOT FINISH` / `PASSED` / `FAILED`) and what no lane covers, printed from the exit path so it appears on early failures and interrupts too.

#324 also fixed a genuine instance of the underlying worry, found while investigating this one: `GhosttyLinuxHeadlessKeyEncodingTests` had been running **zero tests in CI** since it was written, because it sat in `run_linux_tests.sh`'s filter list while `Package.swift`'s Linux `sources:` whitelist omitted its file — and `swift test --filter` that matches nothing exits 0. That lane is now guarded against a zero-match run.
