### ISSUE TITLE
Swift cooperative pool can starve detached tasks for 30+s under machine-wide CPU saturation

### ISSUE THREAD

**Issue by yogesh-dhande** [yogesh-dhande/spaces#236]
## Symptom

Under extreme CPU oversubscription (reproduced with 20 saturating processes alongside a test run), a `Task.detached` block can sit unscheduled for 30+ seconds: the Swift global concurrent executor requests a cooperative-pool thread and the kernel workqueue does not grant one while the machine is saturated. Observed via `RemoteAgentWatchServiceTests.testStartupBaselineLoadPersistsSeedMergedUnion` timing out its full 30s ceiling in 5 of 40 runs under that load.

A thread sample of a hung run shows the decisive picture:

- the main thread idle in the test's poll loop (`mach_msg2_trap`, run loop asleep — no pending main-queue work),
- two ordinary workqueue threads parked idle in `__workq_kernreturn`,
- **no cooperative-pool thread in the process at all**, and no frame anywhere in the startup load's `SQLiteStore` read.

Nothing is blocked on a lock or semaphore; the queued task has no thread to run on. Distinct from the two test-side bugs fixed alongside the investigation (a semaphore-gated transport closure that blocked the pool's only thread, and the load formerly running at `.utility` priority).

## Realistic exposure

Low. The trigger requires oversubscription well beyond a normal `verify.sh` run (which itself runs the macOS test lane and the iOS xcodebuild lane concurrently); repeated full verify runs do not reproduce it after the fixes above. GitHub-hosted ~3-core runners are the most plausible real-world site if their load characteristics worsen.

## Future consideration: dedicated executor for blocking work

The daemon routinely runs syscall-blocking work (SQLite opens/reads/writes, process-spawn waits) inside `Task.detached` closures, i.e. on cooperative-pool threads. That is what gives both this starvation and the blocked-pool class of hazard their teeth, and it is the same pattern flagged from the product side in #212, #219, and #220 (SQLite work stalling the engine actor).

Rather than migrating any of this back to GCD (giving up actor isolation, compile-time data-race safety, and structured cancellation), the principled fix is to keep the Swift concurrency surface and give blocking work its own threads underneath: task executor preference (SE-0417) or a custom actor executor backed by a dispatch queue — e.g. a database executor that owns `SQLiteStore` access. Blocking work then never occupies the cooperative pool, which removes this starvation exposure and the never-block-the-pool constraint structurally. Worth designing once, since it would also address the inline-write stalls tracked in the issues above.

## Acceptance

Either the dedicated-executor design lands for the blocking hot spots (database access first), or this remains documented as the known explanation for a `Task.detached`-dependent wait timing out under machine-wide saturation despite generous ceilings.

**Comment by yogesh-dhande** [comment]
## Another manifestation site: `HostManagedPTYAdoptTests`

Seen once during a local `scripts/verify.sh` run, and worth recording because it is a different test from the one in the description and points at process reaping rather than a SQLite read.

```
HostManagedPTYAdoptTests.swift:95: error: testTerminateReturnsPromptlyAndReapsChildHoldingPTYSlaveOpen :
XCTAssertTrue failed - child was not reaped after terminate()
```

The assertion is `waitUntil(timeout: 10) { kill(childPID, 0) != 0 && errno == ESRCH }`. `terminate()` is documented in that test as doing "only bookkeeping + SIGHUP + a detached escalation" — so the reap depends on a `Task.detached` escalation ladder being scheduled, which is exactly the starvation this issue describes. The earlier `terminate()` promptness assertion in the same test passed, so the call itself returned fine; only the detached follow-up did not run in time.

Load context matches the "realistic exposure" note: since #237 the gate deliberately runs the SwiftPM coverage lane and the iOS `xcodebuild` lane concurrently, so every verify run carries that oversubscription.

Evidence it is this and not a product regression:
- The suite passes in isolation immediately afterward (10/10).
- A full `verify.sh` rerun on the identical tree passes with zero failures in the suite.
- The change under test touched only sidebar/device-routing and terminal-pane banner code; `spacesterminalghostty` does not depend on the edited modules, and nothing in the PTY, terminate, or reaping path was modified.

Not filing separately since the mechanism is the one already tracked here. If the dedicated-executor direction in the description is taken up, this test is a second beneficiary.
